using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace RWGenerators;

[Generator]
public class ConfigAccessorsGenerator : IIncrementalGenerator
{
    internal record class GeneratedClassInfo(
        string Name,
        string Namespace,
        string SourceFullName,
        EquatableArray<(string Name, string Type)> Configurables)
    {}

    public const string AttributeName = "GenerateConfigAccessorsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(AddAttribute);

        IncrementalValuesProvider<GeneratedClassInfo> generatedClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName("RWGenerators.GenerateConfigAccessorsAttribute",
                (_, _) => true,
                GetGeneratedClassInfo)
            .Where(x => x != null)!;

        context.RegisterSourceOutput(generatedClasses, GenerateSource);
    }

    private void AddAttribute(IncrementalGeneratorPostInitializationContext ctx)
    {
        ctx.AddEmbeddedAttributeDefinition();
        ctx.AddSource($"{AttributeName}.g.cs", $@"// <auto-generated/>
using System;

namespace RWGenerators;

/// <summary>
/// Generate class with accessors to values of static Configurable<T> fields and properties
/// </summary>
[Microsoft.CodeAnalysis.Embedded]
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public class {AttributeName}(string className) : Attribute
{{
    public string ClassName {{ get; }} = className;
}}");
    }

    private GeneratedClassInfo? GetGeneratedClassInfo(GeneratorAttributeSyntaxContext ctx, CancellationToken cancellationToken)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol
            || ctx.TargetNode is not ClassDeclarationSyntax classSyntax)
        {
            return null;
        }

        AttributeData attributeData = ctx.Attributes[0];
        if (attributeData.ConstructorArguments.First().Value is not string attributeArgument)
            return null;

        (string generatedName, string? generatedNamespace) = Utils.SplitNameAndNamespace(attributeArgument);
        generatedNamespace ??= Utils.GetDeclarationNamespace(classSyntax);

        List<(string Name, string Type)> configurables = [];
        foreach (IPropertySymbol symbol in classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(s => s.IsStatic && s.IsReadOnly && s.Type.Name == "Configurable"))
        {
            if (symbol.Type is INamedTypeSymbol genericType)
            {
                configurables.Add((symbol.Name, genericType.TypeArguments[0].Name));
            }
        }
        foreach (IFieldSymbol symbol in classSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(s => s.IsStatic && !s.Name.EndsWith("k__BackingField") && s.Type.Name == "Configurable"))
        {
            if (symbol.Type is INamedTypeSymbol genericType)
            {
                configurables.Add((symbol.Name, genericType.TypeArguments[0].Name));
            }
        }

        return new GeneratedClassInfo(
            generatedName,
            generatedNamespace,
            classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            [..configurables]
        );
    }

    private void GenerateSource(SourceProductionContext ctx, GeneratedClassInfo generatedClassInfo)
    {
        StringBuilder generatedProperties = new();
        foreach ((string Name, string Type) in generatedClassInfo.Configurables)
        {
            generatedProperties.Append($"    public static {Type} {Name} => {generatedClassInfo.SourceFullName}.{Name}.Value;");
            generatedProperties.AppendLine();
        }

        ctx.AddSource($"{generatedClassInfo.Name}.g.cs", $@"// <auto-generated/>
namespace {generatedClassInfo.Namespace};

public static partial class {generatedClassInfo.Name}
{{
{generatedProperties}
}}
");
    }
}
